/**
 * 爱情金句库 - 365条精选名人名言
 * 来源：朱生豪、沈从文、王小波、莎士比亚、简·奥斯汀等中外名家
 * 用于"遇见·金句"日历组件
 */

const LOVE_QUOTES = [
  // ========== 朱生豪 (1-30) ==========
  { content: "醒来觉得甚是爱你。", author: "朱生豪" },
  { content: "不要愁老之将至，你老了一定很可爱。", author: "朱生豪" },
  { content: "要是世上只有我们两个人多么好，我一定要把你欺负得哭不出来。", author: "朱生豪" },
  { content: "我愿意舍弃一切，以想念你终此一生。", author: "朱生豪" },
  { content: "我想作诗，写雨，写夜的相思，写你，写不出。", author: "朱生豪" },
  { content: "接到你的信，真快活，风和日暖，令人愿意永远活下去。", author: "朱生豪" },
  { content: "我真疼你疼你，希望没有大狼会来驮了你去。", author: "朱生豪" },
  { content: "与举世绝缘的我，只有你能在我身上引起感应。", author: "朱生豪" },
  { content: "我爱你永远爱不完，愿蚊子不要叮你。", author: "朱生豪" },
  { content: "我的快乐即是爱你。", author: "朱生豪" },
  { content: "从不曾想到要爱你像自己生命一般。", author: "朱生豪" },
  { content: "其实我只要你稍为有点欢喜我，就已心满意足了。", author: "朱生豪" },
  { content: "我发疯似地祝你好！", author: "朱生豪" },
  { content: "许我和你偎一偎脸颊。", author: "朱生豪" },
  { content: "我爱你，不和你谈君子之交。", author: "朱生豪" },
  { content: "为什么我一想起你来，你总是那么小，小得可以藏在衣袋里？", author: "朱生豪" },
  { content: "书隔一星期，历七千万万世纪，思君意如火山爆发。", author: "朱生豪" },
  { content: "我一天一天明白你的平凡，同时却一天一天愈更深切地爱你。", author: "朱生豪" },
  { content: "你如照镜子，你不会看得见你特别好的所在，但你如走进我的心里来时，你一定能知道自己是怎样好法。", author: "朱生豪" },
  { content: "我想要在茅亭里看雨、假山边看蚂蚁，看蝴蝶恋爱，看蜘蛛结网，看水，看船，看云，看瀑布，看你甜甜地睡觉。", author: "朱生豪" },
  { content: "不许你再叫我先生，否则我要从字典中查出世界上最肉麻的称呼来称呼你。", author: "朱生豪" },
  { content: "希望你快乐，不要挂念我。", author: "朱生豪" },
  { content: "你的信很迟，走了很长的路，经过很多人的手，在这颗心里落了根。", author: "朱生豪" },
  { content: "今天的风吹向你下了班我便吹向你。", author: "朱生豪" },
  { content: "你不来，我怎敢老去。", author: "朱生豪" },
  { content: "世界上再也没有一个人像你一样令我快乐。", author: "朱生豪" },
  { content: "我是，我是你的。", author: "朱生豪" },
  { content: "你这个人，总是叫人挂念。", author: "朱生豪" },
  { content: "我多想拥抱你，可惜时光之里山南水北，可惜你我中间人来人往。", author: "朱生豪" },
  { content: "不要问我心里有没有你，我余光中都是你。", author: "朱生豪" },

  // ========== 沈从文 (31-60) ==========
  { content: "我走过无数的桥，看过无数的云，喝过无数种类的酒，却只爱过一个正当最好年纪的人。", author: "沈从文" },
  { content: "我明白你会来，所以我等。", author: "沈从文" },
  { content: "我们相爱一生，一生还是太短。", author: "沈从文" },
  { content: "在青山绿水之间，我想牵着你的手，走过这座桥，桥上是绿叶红花，桥下是流水人家，桥的那头是青丝，桥的这头是白发。", author: "沈从文" },
  { content: "水是各处可流的，火是各处可烧的，月亮是各处可照的，爱情是各处可到的。", author: "沈从文" },
  { content: "我先以为我是个受得了寂寞的人，现在方明白我们自从在一处后，我就变成一个不能同你离开的人了。", author: "沈从文" },
  { content: "想起你我就忍受不了目前的一切了。", author: "沈从文" },
  { content: "我得同你在一处，这心才能安静，事也才能做好！", author: "沈从文" },
  { content: "我感觉得到，我的船在轻轻的摇动，这正同摇篮一样，把人摇得安眠，梦也十分和平。", author: "沈从文" },
  { content: "等待你的时候，我的心就像荒芜的沙漠期待着雨水的滋润。", author: "沈从文" },
  { content: "带着你的香味入眠，是我最美好的梦境。", author: "沈从文" },
  { content: "你的微笑是我永远的向往，我情愿为你做任何事情。", author: "沈从文" },
  { content: "在你的怀抱中，我的心灵得到最温柔的安慰。", author: "沈从文" },
  { content: "有你的陪伴，我愿意遍历千山万水。", author: "沈从文" },
  { content: "我用手去触摸你的眼睛，太冷了。倘若你的眼睛这样冷，有个人的心会结成冰。", author: "沈从文" },
  { content: "一个士兵要不战死沙场，便是回到故乡。", author: "沈从文" },
  { content: "我行过许多地方的桥，看过许多次数的云，喝过许多种类的酒，却只爱过一个正当最好年龄的人。", author: "沈从文" },
  { content: "热情既使人疯狂糊涂，也使人明澈深思。", author: "沈从文" },
  { content: "日头没有辜负我们，我们也切莫辜负日头。", author: "沈从文" },
  { content: "凡事都有偶然的凑巧，结果却又如宿命的必然。", author: "沈从文" },
  { content: "一个人记得事情太多真不幸，知道事情太多也不幸，体会到太多事情也不幸。", author: "沈从文" },
  { content: "这个人也许永远不回来了，也许明天回来。", author: "沈从文" },
  { content: "有些人是可以用时间轻易抹去的，犹如尘土。", author: "沈从文" },
  { content: "我要你，要你同我两人来到这小船上，才有意思！", author: "沈从文" },
  { content: "如今还只是四分之一的别离，已经当不住了，还有二十天，这二十天怎么办！", author: "沈从文" },
  { content: "值得回忆的哀乐人事常是湿的。", author: "沈从文" },
  { content: "生命都是太脆薄的一种东西，并不比一株花更经得住年月风雨。", author: "沈从文" },
  { content: "我这一辈子，走过许多地方的路，行过许多地方的桥，看过许多次数的云，喝过许多种类的酒，却只爱过一个正当年龄的人。", author: "沈从文" },
  { content: "那种日子像水流入海，只让这颗心记着最好的事。", author: "沈从文" },
  { content: "我对这个世界没有什么好说的。", author: "沈从文" },

  // ========== 王小波 (61-100) ==========
  { content: "我把我整个灵魂都给你，连同它的怪癖，耍小脾气，忽明忽暗，一千八百种坏毛病。它真讨厌，只有一点好，爱你。", author: "王小波" },
  { content: "你要是愿意，我就永远爱你，你要是不愿意，我就永远相思。", author: "王小波" },
  { content: "你是非常可爱的人，真应该遇到最好的人，我也真希望我就是。", author: "王小波" },
  { content: "你好哇，李银河。", author: "王小波" },
  { content: "你是我的战友，因此我想念你，当我跨过沉沦的一切，向着永恒开战的时候，你是我的军旗。", author: "王小波" },
  { content: "我对好多人怀有最深的感情，尤其是对你。", author: "王小波" },
  { content: "你真好，我真爱你。可惜我不是诗人，说不出动人一点的话了。", author: "王小波" },
  { content: "做梦也想不到我把信写到五线谱上吧？五线谱是偶然来的，你也是偶然来的。但愿我和你，是一支唱不完的歌。", author: "王小波" },
  { content: "我现在就很高兴，因为你又好又喜欢我。", author: "王小波" },
  { content: "要是这路上的九十分钟省下来和你待在一起多好。", author: "王小波" },
  { content: "我绝不为了仪式爱你，我是正经爱你呢。", author: "王小波" },
  { content: "我喜欢夏天，夏天晚上睡得晚，可以和你在一起，只要你不腻的话。", author: "王小波" },
  { content: "单单你的名字就够我爱一生一世的了。", author: "王小波" },
  { content: "你回来时，我准比上次还爱你呢。", author: "王小波" },
  { content: "我老把和你在一起的时间当成节日来度过，我看你也是。", author: "王小波" },
  { content: "我和你就好像两个小孩子，围着一个秘密的果酱罐，一点一点地尝它，看看里面有多少甜。", author: "王小波" },
  { content: "不管我本人多么平庸，我总觉得对你的爱很美。", author: "王小波" },
  { content: "告诉你，一想到你，我这张丑脸上就泛起微笑。", author: "王小波" },
  { content: "我不知道我有多喜欢你，我只知道，如果是去见你，我一定用跑的。", author: "王小波" },
  { content: "你知道我对你的爱情是什么吗？就是从心底喜欢你，觉得你的一举一动都很亲切。", author: "王小波" },
  { content: "将来啊，我们要是兴致都高涨就一起出来疯跑，你兴致不高就来吧：哭也好，说也好，懒也好，我都喜欢你。", author: "王小波" },
  { content: "只要我们能在一起，我们什么都能找到。", author: "王小波" },
  { content: "也许缺乏勇气是达到美好境界的障碍。你看我是多么适合你的人。我的勇气和你的勇气加起来，对付这个世界总够了吧？", author: "王小波" },
  { content: "我还不算太笨，还能干好多事情。我要自我完善起来，为了你我要成为完人。", author: "王小波" },
  { content: "你一来，我就决心正经的，不是马虎地活下去，哪怕要费心费力，哪怕要我牺牲呢。", author: "王小波" },
  { content: "你生了气就哭，我一看见你哭就目瞪口呆，就像一个小孩子做了坏事在未受责备之前。", author: "王小波" },
  { content: "我很讨厌我自己不温不凉的思虑过度，也许我是个坏人，不过我只要你吻我一下就会变好呢。", author: "王小波" },
  { content: "总之，我认为人不应当忽视自己，生活就是自己啊。比方说我要无愧于自己就要好好爱你才对。", author: "王小波" },
  { content: "今天我生日，徒长一岁何乐之有？何况你又不在。", author: "王小波" },
  { content: "你还有很长很美的人生，不要遇到一点事儿就觉得是世界末日了。", author: "王小波" },
  { content: "爱你就像爱生命。", author: "王小波" },
  { content: "一个人只拥有此生此世是不够的，他还应该拥有诗意的世界。", author: "王小波" },
  { content: "静下来想你，觉得一切都美好得不可思议。", author: "王小波" },
  { content: "我是爱你的，看见就爱上了。我爱你爱到不自私的地步。", author: "王小波" },
  { content: "就像一个人手里一只鸽子飞走了，他从心里祝福那鸽子的飞翔。你也飞吧。", author: "王小波" },
  { content: "还有在我安静的时候，你就从我内心深处浮现，就好像阿芙罗蒂从浪花里浮现一样。", author: "王小波" },
  { content: "一见钟情这种事浪漫，但不一定长久。日久生情这种事很难，却更难分开。", author: "王小波" },
  { content: "自爱，沉稳，而后爱人。", author: "王小波" },
  { content: "只怕爱的太早，不能和你终老。", author: "王小波" },
  { content: "爱情的路上，两个人就好，三个人太多。", author: "王小波" },

  // ========== 中国古典诗词 (101-150) ==========
  { content: "死生契阔，与子成说。执子之手，与子偕老。", author: "《诗经》" },
  { content: "上邪！我欲与君相知，长命无绝衰。山无陵，江水为竭，冬雷震震，夏雨雪，天地合，乃敢与君绝！", author: "汉乐府" },
  { content: "曾经沧海难为水，除却巫山不是云。", author: "元稹" },
  { content: "身无彩凤双飞翼，心有灵犀一点通。", author: "李商隐" },
  { content: "红豆生南国，春来发几枝。愿君多采撷，此物最相思。", author: "王维" },
  { content: "衣带渐宽终不悔，为伊消得人憔悴。", author: "柳永" },
  { content: "两情若是久长时，又岂在朝朝暮暮。", author: "秦观" },
  { content: "此情无计可消除，才下眉头，却上心头。", author: "李清照" },
  { content: "问世间，情是何物，直教生死相许？", author: "元好问" },
  { content: "玲珑骰子安红豆，入骨相思知不知。", author: "温庭筠" },
  { content: "春蚕到死丝方尽，蜡炬成灰泪始干。", author: "李商隐" },
  { content: "愿得一心人，白头不相离。", author: "卓文君" },
  { content: "一日不见，如三秋兮。", author: "《诗经》" },
  { content: "在天愿作比翼鸟，在地愿为连理枝。", author: "白居易" },
  { content: "相思相见知何日？此时此夜难为情。", author: "李白" },
  { content: "天涯地角有穷时，只有相思无尽处。", author: "晏殊" },
  { content: "若似月轮终皎洁，不辞冰雪为卿热。", author: "纳兰性德" },
  { content: "人生自是有情痴，此恨不关风与月。", author: "欧阳修" },
  { content: "换我心，为你心，始知相忆深。", author: "顾敻" },
  { content: "夜月一帘幽梦，春风十里柔情。", author: "秦观" },
  { content: "明月楼高休独倚，酒入愁肠，化作相思泪。", author: "范仲淹" },
  { content: "落花人独立，微雨燕双飞。", author: "晏几道" },
  { content: "天长地久有时尽，此恨绵绵无绝期。", author: "白居易" },
  { content: "直道相思了无益，未妨惆怅是清狂。", author: "李商隐" },
  { content: "只愿君心似我心，定不负相思意。", author: "李之仪" },
  { content: "春心莫共花争发，一寸相思一寸灰。", author: "李商隐" },
  { content: "月上柳梢头，人约黄昏后。", author: "欧阳修" },
  { content: "相思一夜梅花发，忽到窗前疑是君。", author: "卢仝" },
  { content: "思君如流水，何有穷已时。", author: "徐干" },
  { content: "结发为夫妻，恩爱两不疑。", author: "苏武" },
  { content: "思君令人老，岁月忽已晚。", author: "《古诗十九首》" },
  { content: "山有木兮木有枝，心悦君兮君不知。", author: "《越人歌》" },
  { content: "盈盈一水间，脉脉不得语。", author: "《古诗十九首》" },
  { content: "既见君子，云胡不喜。", author: "《诗经》" },
  { content: "愿我如星君如月，夜夜流光相皎洁。", author: "范成大" },
  { content: "梧桐树，三更雨，不道离情正苦。", author: "温庭筠" },
  { content: "晓看天色暮看云，行也思君，坐也思君。", author: "唐寅" },
  { content: "平生不会相思，才会相思，便害相思。", author: "徐再思" },
  { content: "直缘感君恩爱一回顾，使我双泪长珊珊。", author: "卢仝" },
  { content: "忆君心似西江水，日夜东流无歇时。", author: "鱼玄机" },
  { content: "相思树底说相思，思郎恨郎郎不知。", author: "梁启超" },
  { content: "情人怨遥夜，竟夕起相思。", author: "张九龄" },
  { content: "花红易衰似郎意，水流无限似侬愁。", author: "刘禹锡" },
  { content: "美人卷珠帘，深坐颦蛾眉。但见泪痕湿，不知心恨谁。", author: "李白" },
  { content: "还君明珠双泪垂，恨不相逢未嫁时。", author: "张籍" },
  { content: "思悠悠，恨悠悠，恨到归时方始休。", author: "白居易" },
  { content: "多情自古伤离别，更那堪冷落清秋节。", author: "柳永" },
  { content: "相见争如不见，有情何似无情。", author: "司马光" },
  { content: "人面不知何处去，桃花依旧笑春风。", author: "崔护" },
  { content: "君问归期未有期，巴山夜雨涨秋池。何当共剪西窗烛，却话巴山夜雨时。", author: "李商隐" },

  // ========== 外国经典 (151-250) ==========
  { content: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { content: "I have for the first time found what I can truly love—I have found you.", author: "Charlotte Brontë" },
  { content: "You pierce my soul. I am half agony. Half hope.", author: "Jane Austen" },
  { content: "I loved her against reason, against promise, against peace, against hope, against happiness.", author: "Charles Dickens" },
  { content: "Just in case you ever foolishly forget; I'm never not thinking of you.", author: "Virginia Woolf" },
  { content: "He stepped down, trying not to look long at her, as if she were the sun.", author: "Leo Tolstoy" },
  { content: "You are my sun, my moon, and all my stars.", author: "E.E. Cummings" },
  { content: "I would rather spend one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { content: "I love you not only for what you are, but for what I am when I am with you.", author: "Elizabeth Barrett Browning" },
  { content: "If I had a flower for every time I thought of you, I could walk through my garden forever.", author: "Alfred Tennyson" },
  { content: "I carry your heart with me (I carry it in my heart).", author: "E.E. Cummings" },
  { content: "The minute I heard my first love story, I started looking for you.", author: "Rumi" },
  { content: "In your light I learn how to love. In your beauty, how to make poems.", author: "Rumi" },
  { content: "Why, darling, I don't live at all when I'm not with you.", author: "Ernest Hemingway" },
  { content: "When I saw you, I fell in love, and you smiled because you knew.", author: "Arrigo Boito" },
  { content: "Grow old along with me! The best is yet to be.", author: "Robert Browning" },
  { content: "If I know what love is, it is because of you.", author: "Hermann Hesse" },
  { content: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { content: "Soul meets soul on lovers' lips.", author: "Percy Bysshe Shelley" },
  { content: "Who, being loved, is poor?", author: "Oscar Wilde" },
  { content: "I do love nothing in the world so well as you – is not that strange?", author: "William Shakespeare" },
  { content: "What greater thing is there for two human souls, than to feel that they are joined for life.", author: "George Eliot" },
  { content: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { content: "How do I love thee? Let me count the ways.", author: "Elizabeth Barrett Browning" },
  { content: "You and I, it's as though we have been taught to kiss in heaven and sent down to earth together.", author: "Boris Pasternak" },
  { content: "All, everything that I understand, I understand only because I love.", author: "Leo Tolstoy" },
  { content: "Each time you happen to me all over again.", author: "Edith Wharton" },
  { content: "If you live to be a hundred, I want to live to be a hundred minus one day, so I never have to live without you.", author: "A.A. Milne" },
  { content: "Love is the emblem of eternity; it confounds all notion of time.", author: "Madame de Staël" },
  { content: "To love or have loved, that is enough. Ask nothing further.", author: "Victor Hugo" },
  { content: "I want to do with you what spring does with the cherry trees.", author: "Pablo Neruda" },
  { content: "It was love at first sight, at last sight, at ever and ever sight.", author: "Vladimir Nabokov" },
  { content: "Doubt thou the stars are fire; Doubt that the sun doth move; Doubt truth to be a liar; But never doubt I love.", author: "William Shakespeare" },
  { content: "My heart is, and always will be, yours.", author: "Jane Austen" },
  { content: "The very first moment I beheld him, my heart was irrevocably gone.", author: "Jane Austen" },
  { content: "You are the finest, loveliest, tenderest, and most beautiful person I have ever known.", author: "F. Scott Fitzgerald" },
  { content: "I have died everyday waiting for you.", author: "Christina Perri" },
  { content: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle" },
  { content: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
  { content: "I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { content: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu" },
  { content: "The greatest thing you'll ever learn is just to love and be loved in return.", author: "Eden Ahbez" },
  { content: "I am catastrophically in love with you.", author: "Cassandra Clare" },
  { content: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { content: "You are my today and all of my tomorrows.", author: "Leo Christopher" },
  { content: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { content: "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.", author: "Angelita Lim" },
  { content: "Love is not about how many days, months, or years you have been together. It's about how much you love each other every single day.", author: "Unknown" },
  { content: "It is not a lack of love, but a lack of friendship that makes unhappy marriages.", author: "Friedrich Nietzsche" },
  { content: "The real lover is the man who can thrill you by kissing your forehead.", author: "Marilyn Monroe" },
  { content: "I have waited for this opportunity for more than half a century, to repeat to you once again my vow of eternal fidelity and everlasting love.", author: "Gabriel García Márquez" },
  { content: "There is no charm equal to tenderness of heart.", author: "Jane Austen" },
  { content: "Take love, multiply it by infinity and take it to the depths of forever... and you still have only a glimpse of how I feel for you.", author: "Unknown" },
  { content: "I need you like a heart needs a beat.", author: "Unknown" },
  { content: "Come live in my heart and pay no rent.", author: "Samuel Lover" },
  { content: "Love is friendship that has caught fire.", author: "Ann Landers" },
  { content: "The heart wants what it wants. There's no logic to these things.", author: "Woody Allen" },
  { content: "In love there are two evils: war and peace.", author: "Horace" },
  { content: "A flower cannot blossom without sunshine, and man cannot live without love.", author: "Max Muller" },
  { content: "True love stories never have endings.", author: "Richard Bach" },
  { content: "For it was not into my ear you whispered, but into my heart.", author: "Judy Garland" },
  { content: "I love you, not only for what you are, but for what I become when I am with you.", author: "Roy Croft" },
  { content: "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.", author: "Helen Keller" },
  { content: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author: "Dr. Seuss" },
  { content: "Love does not consist of gazing at each other, but in looking outward together in the same direction.", author: "Antoine de Saint-Exupéry" },
  { content: "At the touch of love everyone becomes a poet.", author: "Plato" },
  { content: "Love is like the wind, you can't see it but you can feel it.", author: "Nicholas Sparks" },
  { content: "I would not wish any companion in the world but you.", author: "William Shakespeare" },
  { content: "You are part of my existence, part of myself.", author: "Charles Dickens" },
  { content: "I fell in love with her courage, her sincerity, and her flaming self respect.", author: "F. Scott Fitzgerald" },
  { content: "We would be together and have our books and at night be warm in bed together with the windows open and the stars bright.", author: "Ernest Hemingway" },
  { content: "There are darknesses in life and there are lights; you are one of the lights, the light of all lights.", author: "Bram Stoker" },
  { content: "It has made me better loving you… it has made me wiser, and easier, and brighter.", author: "Henry James" },
  { content: "The smell of her hair, the taste of her mouth, the feeling of her skin seemed to have got inside him.", author: "George Orwell" },
  { content: "I look at you and I would rather look at you than all the portraits in the world.", author: "Frank O'Hara" },
  { content: "You are dearer to me than language has the power of telling.", author: "George Eliot" },
  { content: "If you remember me, then I don't care if everyone else forgets.", author: "Haruki Murakami" },
  { content: "There is never a time or place for true love. It happens accidentally, in a heartbeat.", author: "Sarah Dessen" },
  { content: "For the two of us, home isn't a place. It is a person. And we are finally home.", author: "Stephanie Perkins" },
  { content: "He felt now that he was not simply close to her, but that he did not know where he ended and she began.", author: "Leo Tolstoy" },
  { content: "I like myself better when I'm with you.", author: "Sarah Dessen" },
  { content: "This was love: a string of coincidences that gathered significance and became miracles.", author: "Arundhati Roy" },
  { content: "I am nothing special; just a common man with common thoughts, but I've loved another with all my heart and soul.", author: "Nicholas Sparks" },
  { content: "To be together is for us to be at once as free as in solitude, as gay as in company.", author: "Virginia Woolf" },
  { content: "If I loved you less, I might be able to talk about it more.", author: "Jane Austen" },
  { content: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { content: "To love another person is to see the face of God.", author: "Victor Hugo" },
  { content: "There is no pretending, I love you, and I shall love you until I die.", author: "Cassandra Clare" },
  { content: "I was yours before I knew it, and you were always mine.", author: "Madeline Miller" },
  { content: "I cannot fix on the hour, or the spot, or the look or the words, which laid the foundation. I was in the middle before I knew that I had begun.", author: "Jane Austen" },
  { content: "Out beyond ideas of wrongdoing and rightdoing there is a field. I'll meet you there.", author: "Rumi" },
  { content: "I once had a thousand desires, but in my one desire to know you, all else melted away.", author: "Rumi" },
  { content: "You are my heart, my life, my one and only thought.", author: "Arthur Conan Doyle" },
  { content: "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.", author: "Maya Angelou" },

  // ========== 现代浪漫语录 (251-365) ==========
  { content: "你是我今生唯一的执着。", author: "佚名" },
  { content: "你的每一个微笑，都是我心中最美的风景。", author: "佚名" },
  { content: "在每个孤独的夜里，想念你是我的慰藉。", author: "佚名" },
  { content: "只要与你相伴，哪怕风雨，我也心安。", author: "佚名" },
  { content: "你是我心中永不褪色的阳光。", author: "佚名" },
  { content: "遇见你，是我一生中最美丽的意外。", author: "佚名" },
  { content: "无论世界多么喧嚣，与你在一起就是我的宁静。", author: "佚名" },
  { content: "爱上你，是我做过的最正确的事。", author: "佚名" },
  { content: "你的过去我来不及参与，但你的未来我奉陪到底。", author: "佚名" },
  { content: "这世界不管多漂亮，都不及你。", author: "佚名" },
  { content: "想牵着你的手，从青春走到白发，直到时间的尽头。", author: "佚名" },
  { content: "一想到你，我的世界就像被阳光洒满，暖暖的，甜甜的。", author: "佚名" },
  { content: "我希望我的每一个故事里，都有你参与。", author: "佚名" },
  { content: "你就是我心中的那道光。", author: "佚名" },
  { content: "只要你想要的，若是我有，我都愿意给你。", author: "佚名" },
  { content: "看着微笑的你，突然觉得自己是世界上最幸福的人。", author: "佚名" },
  { content: "我的爱，像潮水，一波波涌来，永不退去。", author: "佚名" },
  { content: "你是我生命中最温柔的注脚。", author: "佚名" },
  { content: "不要轰轰烈烈的爱情，只要你平平淡淡的陪伴。", author: "佚名" },
  { content: "跟你在一起的每一天，都是情人节。", author: "佚名" },
  { content: "你的名字，是我所有快乐的开始。", author: "佚名" },
  { content: "我们相遇，不是偶然，而是宿命的安排。", author: "佚名" },
  { content: "最好的爱情，就是可以快乐地做自己，还依然被爱着。", author: "佚名" },
  { content: "世界上最温暖的两个字，是你的名字。", author: "佚名" },
  { content: "愿时光能缓，愿你我能相伴。", author: "佚名" },
  { content: "从今往后，风筝有风，海豚有海，你有我。", author: "佚名" },
  { content: "喜欢你这件事，是毋庸置疑的绝对真理。", author: "佚名" },
  { content: "你永远是我的特别关心和置顶。", author: "佚名" },
  { content: "月亮不睡你不睡，你是秃头小宝贝。", author: "佚名" },
  { content: "我对你的喜欢，像春天的风，像夏天的雨，像秋天的云，像冬天的雪。", author: "佚名" },
  { content: "我想和你见面，地点你选，森林、沙漠、夜晚依偎的街边，只要别在梦里。", author: "佚名" },
  { content: "想把每一个日落都拍下来寄给你，让你知道，我比昨天更想你。", author: "佚名" },
  { content: "人生建议：和喜欢的人多待在一起。", author: "佚名" },
  { content: "你是我隐匿多年，不愿提笔写出的旧事。", author: "佚名" },
  { content: "你眼中有星河，是我从未见过的美景。", author: "佚名" },
  { content: "喜欢你，是一件既甜蜜又痛苦的事。", author: "佚名" },
  { content: "愿你眼里有光芒，心里有远方，愿你走过半生，归来仍是少年。", author: "佚名" },
  { content: "你是我心里的一首歌，旋律优美动人。", author: "佚名" },
  { content: "我喜欢你，从黑夜到黎明，从宇宙到微尘。", author: "佚名" },
  { content: "春风十里不如你，梦里梦外都是你。", author: "佚名" },
  { content: "你是我翘首以盼的惊喜，也是我始料未及的心动。", author: "佚名" },
  { content: "我见青山多妩媚，料青山见我应如是。", author: "辛弃疾" },
  { content: "山水一程，三生有幸。", author: "佚名" },
  { content: "情不知所起，一往而深。", author: "汤显祖" },
  { content: "愿有岁月可回首，且以深情共白头。", author: "佚名" },
  { content: "你是我的今天，也是我所有的明天。", author: "佚名" },
  { content: "余生请多指教。", author: "佚名" },
  { content: "遇见你之后，理想不再是骑马喝酒去天涯，而是再晚我也要回家。", author: "佚名" },
  { content: "你要是冷了，我就把我心里对你的爱，如数奉上。", author: "佚名" },
  { content: "终于等到你，还好我没放弃。", author: "佚名" },
  { content: "你是我的小确幸，也是我的大运气。", author: "佚名" },
  { content: "你是我心动的开始，也是我心安的归处。", author: "佚名" },
  { content: "我愿意用一生换取一世的相守。", author: "佚名" },
  { content: "我这一生最大的幸运，就是遇见你。", author: "佚名" },
  { content: "你说，你爱我。我听了一辈子。", author: "佚名" },
  { content: "我不知道什么是爱，直到遇见你。", author: "佚名" },
  { content: "你是我余生的风景，我愿意为你画一辈子。", author: "佚名" },
  { content: "你是我见过最美丽的风景。", author: "佚名" },
  { content: "你是我心里的小太阳，照亮了我所有的时光。", author: "佚名" },
  { content: "遇见你，是我人生最美的意外。", author: "佚名" },
  { content: "我想和你一起浪费时间，浪费生命。", author: "佚名" },
  { content: "你是我最大的软肋，也是我最坚硬的铠甲。", author: "佚名" },
  { content: "我不会说情话，只想把你带回家。", author: "佚名" },
  { content: "世间五味俱全，谢谢你给我的甜。", author: "佚名" },
  { content: "我想陪你走过这漫长的岁月，直到发丝都变白。", author: "佚名" },
  { content: "喜欢你的眼睛，里面有我喜欢的星星和月亮。", author: "佚名" },
  { content: "你是我永远的春天。", author: "佚名" },
  { content: "我在等风，也等你。", author: "佚名" },
  { content: "我想陪你一起看日出日落。", author: "佚名" },
  { content: "世界很大，而我只想住在你心里。", author: "佚名" },
  { content: "你是我心口的朱砂，抹不去的牵挂。", author: "佚名" },
  { content: "我只是想和你在一起，简简单单的。", author: "佚名" },
  { content: "陪你到最后，是我的承诺。", author: "佚名" },
  { content: "我喜欢你，像风走了八千里，不问归期。", author: "佚名" },
  { content: "你是我穷极一生都想追寻的美好。", author: "佚名" },
  { content: "我的世界因你而完整。", author: "佚名" },
  { content: "你是我心里的一颗糖，甜到忧伤。", author: "佚名" },
  { content: "我想和你一起变老。", author: "佚名" },
  { content: "遇见你之后，生命才有了意义。", author: "佚名" },
  { content: "你是我的例外，也是我的偏爱。", author: "佚名" },
  { content: "愿岁月可回首，深情共白头。", author: "佚名" },
  { content: "我的心里只有你，没有其他。", author: "佚名" },
  { content: "你是我三生有幸的遇见。", author: "佚名" },
  { content: "你眼里有星辰大海，是我一生的浪漫。", author: "佚名" },
  { content: "喜欢你，是我做过最勇敢的事。", author: "佚名" },
  { content: "你是我写不完的诗，读不完的书。", author: "佚名" },
  { content: "只要你在，我的心就是满的。", author: "佚名" },
  { content: "你是我心动的理由，也是我不想放手的原因。", author: "佚名" },
  { content: "世界那么大，能遇见你，真的很幸运。", author: "佚名" },
  { content: "我想要的未来，是有你的未来。", author: "佚名" },
  { content: "你是我生命中的阳光，温暖了我的每一天。", author: "佚名" },
  { content: "我愿意等你，不管多久。", author: "佚名" },
  { content: "你在，我的心就安稳。", author: "佚名" },
  { content: "你是我最美的意外，也是我最深的期待。", author: "佚名" },
  { content: "我想和你一起，慢慢变老。", author: "佚名" },
  { content: "遇见你，我变成了更好的自己。", author: "佚名" },
  { content: "你是我的全世界，没有你，世界都是灰色的。", author: "佚名" },
  { content: "我的心里，只有你一个人的位置。", author: "佚名" },
  { content: "你是我生命中的奇迹。", author: "佚名" },
  { content: "想和你一起，看遍世间所有的美景。", author: "佚名" },
  { content: "你是我不想醒来的梦。", author: "佚名" },
  { content: "我喜欢你，从始至终，认真且怂。", author: "佚名" },
  { content: "你是我想写的信，想送的花，想见的人。", author: "佚名" },
  { content: "把你的名字，写在我心上。", author: "佚名" },
  { content: "你是我想珍藏的时光。", author: "佚名" },
  { content: "我把思念揉进风里，让它带你身边。", author: "佚名" },
  { content: "愿你我既是知己，也是爱人。", author: "佚名" },
  { content: "我心悦你，只此一人，绝无仅有。", author: "佚名" },
  { content: "每一个撕下日历的日子，都是我们在相爱。", author: "Coria & Minnie" }
];

// 导出模块（兼容ES Module和CommonJS）
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { LOVE_QUOTES };
}
